version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: analyticore_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  python-service:
    build:
      context: ./python-service
    container_name: analyticore_python
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
      JAVA_SERVICE_URL: http://java-service:8080
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  java-service:
    build:
      context: ./java-service
    container_name: analyticore_java
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: analyticore_frontend
    ports:
      - "3000:80"
    depends_on:
      - python-service

volumes:
  postgres_data:
