version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analyticore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python-service:
    build: 
      context: ./python-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/analyticore
      - JAVA_SERVICE_URL=http://java-service:8080
    depends_on:
      - db

  java-service:
    build: 
      context: ./java-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/analyticore
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - python-service

volumes:
  pgdata:
